# Generated by Django 4.2.9 on 2024-04-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_numerourgence_stock_name_stock_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
