# Generated by Django 4.2.9 on 2024-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_stock_name_alter_stock_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='number',
        ),
        migrations.AddField(
            model_name='numerourgence',
            name='name',
            field=models.CharField(default='numero urgence', max_length=100),
        ),
        migrations.AddField(
            model_name='numerourgence',
            name='number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
