# Generated by Django 4.2.9 on 2024-04-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
